#' Get the table and foreign key info for a database from its internal schema
#'
#' @param conn Database connection
#'
#' @returns A list with two data frames, one with table info, one with foreign keys
#' @export
#'
schemaInfo <- function(conn) {
  tables <- dbListTables(conn)

  # Get the table info (attributes and which are PK)
  tableInfo <- lapply(tables, function(table) {
    dbGetQuery(conn, sprintf('PRAGMA table_info("%s");', table)) |>
      mutate(table = {{ table }})
  })
  tableInfo <- do.call(bind_rows, tableInfo) |> select(table, everything())

  #Get the foreign keys for each table that has them
  foreignkeyInfo <- lapply(tables, function(table) {
    info <- dbGetQuery(conn, sprintf("PRAGMA foreign_key_list(%s);", table)) |>
      mutate(fk_table = table, table = {{ table }})
    if (nrow(info) == 0) {
      return(NULL)
    }
    info
  })
  foreignkeyInfo <- do.call(bind_rows, foreignkeyInfo) |>
    select(table, from, to, fk_table, everything())

  return(list(tableInfo = tableInfo, foreignkeyInfo = foreignkeyInfo))
}

#' Check primary and foreign keys for a given schema
#'
#' @param schemainfo Generated by schemaInfo
#' @param exclude (Default = "sqlite_sequence") Tables to exclude.
#' The sqlite_sequence table is auto generated for auto incrementing keys
#' and should be ignored
#'
#' @returns A list with a status code and two dataframes on PK and FK results.
#' Status code 1: no isses, -1: PK issues, -2 FK issues, -3 PK & FK issues
#' @export
#'
keyCheck <- function(schemainfo, exclude = c("sqlite_sequence")) {
  # Each table at least has one PK
  PKcheck <- schemainfo$tableInfo |>
    filter(!table %in% exclude) |>
    group_by(table) |>
    summarise(hasPK = any(pk == 1), .groups = "drop")

  statusCode <- ifelse(any(!PKcheck$hasPK), -1, 1)

  # The foreign keys must ...
  # - Be primary keys in the table or origin
  # - Include all keys in case of a composite key
  foreignkeyInfo <- schemainfo$foreignkeyInfo |>
    select(table, from, to, fk_table)

  FKcheck <- lapply(unique(foreignkeyInfo$table), function(table) {
    fks <- foreignkeyInfo |> filter(table == {{ table }})
    schemainfo$tableInfo |>
      filter(table %in% fks$fk_table) |>
      select(fk_table = table, to = name, pk) |>
      left_join(
        fks |> select(table, from, to, fk_table),
        by = c("fk_table", "to")
      ) |>
      mutate(table = {{ table }}) |>
      filter(pk != 0 | !is.na(from))
  })

  FKcheck <- do.call(bind_rows, FKcheck) |>
    select(table, from, to, fk_table, pk) |>
    mutate(
      reason = case_when(
        pk == 0 ~ "mapToNonPK",
        is.na(from) ~ "missingCompoundKey",
        TRUE ~ ""
      ),
      issue = reason != ""
    )

  statusCode <- case_when(
    !any(FKcheck$issue) ~ statusCode,
    any(FKcheck$issue) & statusCode == -1 ~ -3,
    TRUE ~ -2
  )

  return(list(statusCode = statusCode, PKcheck = PKcheck, FKcheck = FKcheck))
}

#' Create a graph from schema info
#'
#' @param schemainfo Generated by the schemaInfo function
#'
#' @importFrom igraph graph_from_data_frame
#' @import dplyr
#'
#' @returns A list with 3 elements: data frame of nodes, edges and a igraph object
#' @export
#'
schemaGraph <- function(schemainfo) {
  tables <- unique(schemainfo$tableInfo$table)
  tables <- data.frame(id = 1:length(tables), label = tables)

  attributes <- schemainfo$tableInfo |>
    mutate(
      id = 1:n() + nrow(tables),
      label = name,
      parent = table,
      .keep = "none"
    )

  # Create the nodes
  nodes <- bind_rows(
    tables |> select(id, label),
    attributes |> select(id, label)
  )

  # For edges, first connect the attributes to their respective table node
  edges <- attributes |>
    select(from = id, parent) |>
    left_join(tables |> select(parent = label, to = id), by = "parent") |>
    select(from, to)

  # Next connect tables by the foreign keys
  edges <- bind_rows(
    edges,
    schemainfo$foreignkeyInfo |>
      select(table, fk_table) |>
      distinct() |>
      left_join(tables |> select(table = label, from = id), by = "table") |>
      left_join(tables |> select(fk_table = label, to = id), by = "fk_table") |>
      select(from, to)
  )

  # Create the graph
  g <- graph_from_data_frame(d = edges, vertices = nodes, directed = F)

  return(list(nodes = nodes, edges = edges, graph = g))
}
