#' Get the table and foreign key info for a database from its internal schema
#'
#' @param conn Database connection
#' @param exclude (Default = "sqlite_sequence") Tables to exclude.
#' The sqlite_sequence table is auto generated for auto incrementing keys
#' and should be ignored
#' @param include (Optional vector) Limit to a set of tables
#'
#' @returns A list with two data frames, one with table info, one with foreign keys
#' @export
#'
schemaInfo <- function(conn, exclude = c("sqlite_sequence"), include) {
  # Check
  if (!missing(include)) {
    include <- unique(include)
    check_names_table(conn, existing = include, error = T)
    tables <- include
  } else {
    tables <- dbListTables(conn)
    tables <- tables[!tables %in% exclude]
  }

  # Get the table info (attributes and which are PK)
  tableInfo <- lapply(tables, function(table) {
    dbGetQuery(conn, sprintf('PRAGMA table_info("%s");', table)) |>
      mutate(table = {{ table }})
  })
  tableInfo <- do.call(bind_rows, tableInfo) |> select(table, everything())

  #Get the foreign keys for each table that has them
  foreignkeyInfo <- lapply(tables, function(table) {
    info <- dbGetQuery(conn, sprintf("PRAGMA foreign_key_list(%s);", table)) |>
      mutate(fk_table = table, table = {{ table }})
    if (nrow(info) == 0) {
      return(NULL)
    }
    info
  })
  foreignkeyInfo <- do.call(bind_rows, foreignkeyInfo) |>
    select(table, from, to, fk_table, everything())

  return(list(tableInfo = tableInfo, foreignkeyInfo = foreignkeyInfo))
}

#' Check primary and foreign keys for a given schema
#'
#' @param schemainfo Generated by schemaInfo
#' @param exclude (Default = "sqlite_sequence") Tables to exclude.
#' The sqlite_sequence table is auto generated for auto incrementing keys
#' and should be ignored
#'
#' @returns A list with a status codes vector, accompanying messages and two
#' dataframes with PK and FK results.
#' Status codes 1: no issues, -1: PK issues,-2 no FK found, -3 FK issues
#' @export
#'
keyCheck <- function(schemainfo, exclude = c("sqlite_sequence")) {
  # Each table at least has one PK
  PKcheck <- schemainfo$tableInfo |>
    filter(!table %in% exclude) |>
    group_by(table) |>
    summarise(hasPK = any(pk == 1), .groups = "drop")

  statusCode <- ifelse(any(!PKcheck$hasPK), -1, 1)

  # The foreign keys must ...
  # - Be primary keys in the table or origin
  # - Include all keys in case of a composite key
  foreignkeyInfo <- schemainfo$foreignkeyInfo |>
    select(table, from, to, fk_table)

  FKcheck <- lapply(unique(foreignkeyInfo$table), function(table) {
    fks <- foreignkeyInfo |> filter(table == {{ table }})
    schemainfo$tableInfo |>
      filter(table %in% fks$fk_table) |>
      select(fk_table = table, to = name, pk) |>
      left_join(
        fks |> select(table, from, to, fk_table),
        by = c("fk_table", "to")
      ) |>
      mutate(table = {{ table }}) |>
      filter(pk != 0 | !is.na(from))
  })

  # Check if there are any foreign keys
  if (length(FKcheck) == 0) {
    # There are none
    FKcheck <- data.frame()
    # No FK are treated as an issue
    if (statusCode == 1) {
      statusCode <- c(-2)
    } else {
      statusCode <- c(-1, -2)
    }
  } else {
    # There are 1 or more
    FKcheck <- do.call(bind_rows, FKcheck) |>
      select(table, from, to, fk_table, pk) |>
      mutate(
        reason = case_when(
          pk == 0 ~ "mapToNonPK",
          is.na(from) ~ "missingCompoundKey",
          TRUE ~ ""
        ),
        issue = reason != ""
      )
    # Check if any have issues
    if (any(FKcheck$issue)) {
      statusCode <- c(statusCode, -3)
    }
  }

  # Remove success code in case of any errors
  if (any(statusCode < 0)) {
    statusCode <- statusCode[statusCode < 0]
    msg <- c()
  } else {
    msg <- c("No (foreign) key issues detected")
  }

  if (-1 %in% statusCode) {
    msg <- paste0(
      "ERROR: The following tables are missing primary keys: ",
      paste(PKcheck |> filter(!hasPK) |> pull(table), collapse = ", ")
    )
  }

  if (-2 %in% statusCode) {
    msg <- c(
      msg,
      paste(
        "WARNING: There a no foreign keys found in the given schema."
      )
    )
  }

  if (-3 %in% statusCode) {
    msg <- c(
      msg,
      paste0(
        "ERROR: The following tables are having foreign key issues:\n",
        dfAsText(FKcheck |> filter(issue))
      )
    )
  }

  return(list(
    statusCode = statusCode,
    msg = msg,
    PKcheck = PKcheck,
    FKcheck = FKcheck
  ))
}

#' Create a graph from schema info
#'
#' @param schemainfo Generated by the schemaInfo function
#'
#' @importFrom igraph graph_from_data_frame
#' @import dplyr
#'
#' @returns A list with 3 elements: a igraph object and two data frames with
#'  of table and attribute info
#' @export
#'
schemaGraph <- function(schemainfo) {
  tables <- unique(schemainfo$tableInfo$table)
  tables <- data.frame(id = 1:length(tables), table = tables)

  attributes <- schemainfo$tableInfo |>
    mutate(
      id = 1:n() + nrow(tables),
      attribute = name,
      table,
      .keep = "none"
    ) |>
    select(id, table, attribute)

  # Create the nodes
  nodes <- bind_rows(
    tables |> select(id, table),
    attributes |> select(id, label = attribute)
  )

  # For edges, first connect the attributes to their respective table node
  edges <- attributes |>
    select(from = id, parent = table) |>
    left_join(tables |> select(parent = table, to = id), by = "parent") |>
    select(from, to)

  # Next connect tables by the foreign keys
  edges <- bind_rows(
    edges,
    schemainfo$foreignkeyInfo |>
      select(table, fk_table) |>
      distinct() |>
      left_join(tables |> select(table, from = id), by = "table") |>
      left_join(tables |> select(fk_table = table, to = id), by = "fk_table") |>
      select(from, to)
  )

  # Create the graph
  g <- graph_from_data_frame(d = edges, vertices = nodes, directed = F)

  return(list(graph = g, tables = tables, attributes = attributes))
}

#' Generate dplyr code to join multiple tables in a database
#'
#'  This function only works if the schema of the database is complete and
#'  all primary and foreign keys have been declared
#'
#' @param conn SQLite connection
#' @param ... Names of tables to join together. The first one listed will be
#' used to join all the others to. Subsequent order depends on the foreign keys
#' @param addSelect (Default = T) Add a dplyr select() function placeholder to the
#' result to later modify the exact columns to select from each table.
#' All primary and relevant foreign keys are automatically included.
#' For tables not listed but needed, only the keys needed for joins are used.
#' @param displayInfo (Default = T) Warning when column names of tables that
#' will be joined clash (intermediate tables are ignored) and message when
#' auto-generated key names are introduced to avoid issues.
#'
#' @import dplyr glue
#' @importFrom igraph shortest_paths
#'
#' @returns The code needed to perform the joins.
dist_join <- function(conn, ..., addSelect = T, displayInfo = T) {
  # Check the input
  toJoin <- as.character(c(...))
  check <- setdiff(toJoin, dbListTables(conn))

  if (length(check) > 0) {
    stop(
      "The following tables are not found in the database: ",
      paste(check, collapse = ", ")
    )
  }

  # Get schema info
  schemainfo <- schemaInfo(conn)
  # Find links between tables via paths in the graph
  schemagraph <- schemaGraph(schemainfo)

  tablesNeeded <- schemagraph$tables |> filter(table %in% toJoin)
  # If no path can be found between the nodes the join is impossible
  withCallingHandlers(
    {
      tablesNeeded <- shortest_paths(
        schemagraph$graph,
        tablesNeeded$id[1],
        tablesNeeded$id[-1]
      )
    },
    warning = function(w) {
      # Subset the schema to the tables needed
      schemainfo <- list(
        tableInfo = schemainfo$tableInfo |> filter(table %in% toJoin),
        foreignkeyInfo = schemainfo$foreignkeyInfo |>
          filter(table %in% toJoin & fk_table %in% toJoin)
      )
      # Check if the schema uses keys correctly
      check <- keyCheck(schemainfo)
      stop(
        "No path can be found connecting all tables due to (foreign) keys issues",
        "\n\n---- MORE INFO ----\n",
        paste(check$msg, collapse = "\n\n")
      )
    }
  )

  tablesNeeded <- tablesNeeded$vpath |> unlist() |> unname() |> unique()
  tablesNeeded <- schemagraph$tables |>
    filter(id %in% tablesNeeded) |>
    pull(table)

  # Subset the schema to the tables needed
  schemainfo <- list(
    tableInfo = schemainfo$tableInfo |> filter(table %in% tablesNeeded),
    foreignkeyInfo = schemainfo$foreignkeyInfo |>
      filter(table %in% tablesNeeded & fk_table %in% tablesNeeded)
  )

  # Check if the schema uses keys correctly
  check <- keyCheck(schemainfo)

  if (!1 %in% check$statusCode) {
    stop(paste(check$msg, collapse = "\n\n"))
  }

  # The linkId groups tables by foreign keys to join them on (in case of compound)
  tablesToJoin <- schemainfo$foreignkeyInfo |>
    select(table, from, to, fk_table) |>
    filter(table %in% tablesNeeded & fk_table %in% tablesNeeded) |>
    group_by(table, fk_table) |>
    mutate(linkId = cur_group_id()) |>
    ungroup()

  allKeys <- bind_rows(
    tablesToJoin |> select(table, name = from) |> mutate(pk = F),
    schemainfo$tableInfo |>
      filter(table %in% tablesNeeded, pk > 0) |>
      select(table, name) |>
      mutate(pk = T)
  ) |>
    group_by(name, pk) |>
    mutate(
      uniqueKey = ifelse(
        rep(n() == 1, n()),
        name,
        paste(table, name, sep = "_")
      )
    ) |>
    ungroup()

  # For now keep this internal, as there likely is not much reason for
  # the other options
  keyFormat = "auto"

  # Figure out which join key is the best one to use
  tablesToJoin <- tablesToJoin |>
    left_join(
      allKeys |>
        filter(!pk) |>
        select(table, from = name, fromUnique = uniqueKey),
      by = c("table", "from")
    ) |>
    left_join(
      allKeys |>
        filter(pk) |>
        select(fk_table = table, to = name, toUnique = uniqueKey),
      by = c("fk_table", "to")
    ) |>
    mutate(
      joinKey = case_when(
        keyFormat == "auto" ~ ifelse(from == fromUnique, from, toUnique),
        keyFormat %in% c("fk", "FK") ~ fromUnique,
        keyFormat %in% c("pk", "PK") ~ toUnique,
        TRUE ~ paste0(table, "_id")
      )
    ) |>
    select(-fromUnique, -toUnique)

  # Check all join keys that were auto generated to be unique
  generated <- allKeys |>
    filter(!uniqueKey %in% name) |>
    select(table, originalKey = name, newKey = uniqueKey)

  if (displayInfo && nrow(generated) > 0) {
    message(
      "The following keys were auto-generated to ensure uniqueness:\n\n",
      dfAsText(generated)
    )
  }

  # Start with the first listed table
  first <- c(
    which(toJoin[1] == tablesToJoin$table),
    which(toJoin[1] == tablesToJoin$fk_table)
  )
  nextLinkId <- tablesToJoin$linkId[first[1]]
  joined = c()
  result = ""

  # Function to add the select() function based on addSelect parameter
  selectPlaceholder <- function(table) {
    # Get all primary keys (start with info from join table)
    PK <- tablesToJoin |> filter(fk_table == {{ table }})

    if (nrow(PK) > 0) {
      PK <- ifelse(
        PK$to == PK$joinKey,
        PK$to,
        paste0(PK$joinKey, '" = "', PK$to, collapse = '", "')
      )
    } else {
      PKinfo <- allKeys |> filter(pk, table == {{ table }})
      PK <- ifelse(
        PKinfo$name == PKinfo$uniqueKey,
        PKinfo$name,
        paste0(PKinfo$uniqueKey, '" = "', PKinfo$name, collapse = '", "')
      )
    }
    # Get all foreign keys needed in any join
    FK <- tablesToJoin |> filter(table == {{ table }})
    FK <- ifelse(
      FK$from == FK$joinKey,
      FK$from,
      paste0(FK$joinKey, '" = "', FK$from, collapse = '", "')
    )
    # Paste everything together
    ifelse(
      addSelect,
      glue(
        '") |> select("',
        paste(unique(c(PK, FK)), collapse = '","'),
        ifelse(table %in% toJoin, '", everything())', '")')
      ),
      ')'
    )
  }

  # Generate the code needed to join the tables
  while (length(nextLinkId) > 0) {
    nextJoin <- tablesToJoin |> filter(linkId == nextLinkId)

    if (result == "") {
      # Flip the tables if the first one provided by user is listed as foreign
      if (nextJoin$fk_table == toJoin[1]) {
        colnames(nextJoin)[1:4] <- c("fk_table", "to", "from", "table")
      }
      # Get the first join
      result = glue(
        'tbl(conn, "',
        nextJoin$table,
        selectPlaceholder(nextJoin$table),
        ' |>\n  left_join(tbl(conn, "',
        nextJoin$fk_table,
        selectPlaceholder(nextJoin$fk_table),
        ', by = c("',
        paste(nextJoin$joinKey, collapse = '", "'),
        '"))'
      )
    } else {
      # Subsequent joins
      check <- nextJoin$table %in% joined
      joinTable <- ifelse(check, nextJoin$fk_table, nextJoin$table)
      result = glue(
        result,
        ' |>\n left_join(tbl(conn, "',
        joinTable,
        selectPlaceholder(joinTable),
        ', by = c("',
        paste(nextJoin$joinKey, collapse = '", "'),
        '"))'
      )
    }
    # Prepare for the next join by picking a table that can be linked to the existing ones
    joined <- c(joined, nextJoin$table, nextJoin$fk_table)
    tablesToJoin <- tablesToJoin |> filter(linkId != nextLinkId)
    nextLinkId <- tablesToJoin |>
      filter(table %in% joined | fk_table %in% joined) |>
      slice(1) |>
      pull(linkId)
  }

  # Check for column names that will clash when joined
  clashing <- schemainfo$tableInfo |>
    filter(table %in% toJoin) |>
    group_by(name) |>
    filter(pk == 0, n() > 1) |>
    ungroup()

  if (displayInfo && nrow(clashing) > 0) {
    warning(
      "The following column names clash when their tables are joined\n",
      dfAsText(as.data.frame(clashing |> select(table, column = name)))
    )
  }

  return(result)
}
