#' Get the table and foreign key info for a database from its internal schema
#'
#' @param conn Database connection
#'
#' @returns A list with two data frames, one with table info, one with foreign keys
#' @export
#'
schemaInfo <- function(conn) {
  tables <- dbListTables(conn)

  # Get the table info (attributes and which are PK)
  tableInfo <- lapply(tables, function(table) {
    dbGetQuery(conn, sprintf('PRAGMA table_info("%s");', table)) |>
      mutate(table = {{ table }})
  })
  tableInfo <- do.call(bind_rows, tableInfo) |> select(table, everything())

  #Get the foreign keys for each table that has them
  foreignkeyInfo <- lapply(tables, function(table) {
    info <- dbGetQuery(conn, sprintf("PRAGMA foreign_key_list(%s);", table)) |>
      mutate(fk_table = table, table = {{ table }})
    if (nrow(info) == 0) {
      return(NULL)
    }
    info
  })
  foreignkeyInfo <- do.call(bind_rows, foreignkeyInfo) |>
    select(table, from, to, fk_table, everything())

  return(list(tableInfo = tableInfo, foreignkeyInfo = foreignkeyInfo))
}

#' Check primary and foreign keys for a given schema
#'
#' @param schemainfo Generated by schemaInfo
#' @param exclude (Default = "sqlite_sequence") Tables to exclude.
#' The sqlite_sequence table is auto generated for auto incrementing keys
#' and should be ignored
#'
#' @returns A list with a status code and two dataframes on PK and FK results.
#' Status code 1: no isses, -1: PK issues, -2 FK issues, -3 PK & FK issues
#' @export
#'
keyCheck <- function(schemainfo, exclude = c("sqlite_sequence")) {
  # Each table at least has one PK
  PKcheck <- schemainfo$tableInfo |>
    filter(!table %in% exclude) |>
    group_by(table) |>
    summarise(hasPK = any(pk == 1), .groups = "drop")

  statusCode <- ifelse(any(!PKcheck$hasPK), -1, 1)

  # The foreign keys must ...
  # - Be primary keys in the table or origin
  # - Include all keys in case of a composite key
  foreignkeyInfo <- schemainfo$foreignkeyInfo |>
    select(table, from, to, fk_table)

  FKcheck <- lapply(unique(foreignkeyInfo$table), function(table) {
    fks <- foreignkeyInfo |> filter(table == {{ table }})
    schemainfo$tableInfo |>
      filter(table %in% fks$fk_table) |>
      select(fk_table = table, to = name, pk) |>
      left_join(
        fks |> select(table, from, to, fk_table),
        by = c("fk_table", "to")
      ) |>
      mutate(table = {{ table }}) |>
      filter(pk != 0 | !is.na(from))
  })

  FKcheck <- do.call(bind_rows, FKcheck) |>
    select(table, from, to, fk_table, pk) |>
    mutate(
      reason = case_when(
        pk == 0 ~ "mapToNonPK",
        is.na(from) ~ "missingCompoundKey",
        TRUE ~ ""
      ),
      issue = reason != ""
    )

  statusCode <- case_when(
    !any(FKcheck$issue) ~ statusCode,
    any(FKcheck$issue) & statusCode == -1 ~ -3,
    TRUE ~ -2
  )

  return(list(statusCode = statusCode, PKcheck = PKcheck, FKcheck = FKcheck))
}

#' Create a graph from schema info
#'
#' @param schemainfo Generated by the schemaInfo function
#'
#' @importFrom igraph graph_from_data_frame
#' @import dplyr
#'
#' @returns A list with 3 elements: a igraph object and two data frames with
#'  of table and attribute info
#' @export
#'
schemaGraph <- function(schemainfo) {
  tables <- unique(schemainfo$tableInfo$table)
  tables <- data.frame(id = 1:length(tables), table = tables)

  attributes <- schemainfo$tableInfo |>
    mutate(
      id = 1:n() + nrow(tables),
      attribute = name,
      table,
      .keep = "none"
    ) |>
    select(id, table, attribute)

  # Create the nodes
  nodes <- bind_rows(
    tables |> select(id, table),
    attributes |> select(id, label = attribute)
  )

  # For edges, first connect the attributes to their respective table node
  edges <- attributes |>
    select(from = id, parent = table) |>
    left_join(tables |> select(parent = table, to = id), by = "parent") |>
    select(from, to)

  # Next connect tables by the foreign keys
  edges <- bind_rows(
    edges,
    schemainfo$foreignkeyInfo |>
      select(table, fk_table) |>
      distinct() |>
      left_join(tables |> select(table, from = id), by = "table") |>
      left_join(tables |> select(fk_table = table, to = id), by = "fk_table") |>
      select(from, to)
  )

  # Create the graph
  g <- graph_from_data_frame(d = edges, vertices = nodes, directed = F)

  return(list(graph = g, tables = tables, attributes = attributes))
}

# toJoin <- list(evaluation = c("id", "complete"), clerkship = "clerkship")
# toJoin <- c("evaluation", "clerkship")

#' Title
#'
#' @param conn SQLite connection
#' @param ... List of tables to join together
#' @param addSelect (Default = T) Add a select() function placeholder to the
#' result to later modify the columns to select from each table
#' @param warnClashes (Default = T) Warning when column names of tables that
#' will be joined clash (intermediate tables are ignored)
#'
#' @import dplyr glue
#' @importFrom igraph shortest_paths
#'
#' @returns Print the code needed to perform the joins. Invisibly returns the
#' string as well
distJoin <- function(conn, ..., addSelect = T, warnClashes = T) {
  # Check the input
  toJoin <- as.character(c(...))
  check <- setdiff(toJoin, dbListTables(conn))
  if (length(check) > 0) {
    stop(
      "The following tables are not found in the database: ",
      paste(check, collapse = ", ")
    )
  }

  # Find links between tables via paths in the graph
  schemainfo <- schemaInfo(conn)
  schemagraph <- schemaGraph(schemainfo)

  tablesToJoin <- schemagraph$tables |> filter(table %in% toJoin)
  tablesToJoin <- shortest_paths(
    schemagraph$graph,
    tablesToJoin$id[1],
    tablesToJoin$id[-1]
  )
  tablesToJoin <- tablesToJoin$vpath |> unlist() |> unname() |> unique()
  tablesToJoin <- schemagraph$tables |> filter(id %in% tablesToJoin)

  # The linkId groups tables by foreign keys to join them on (in case of compound)
  tablesToJoin <- schemainfo$foreignkeyInfo |>
    select(table, from, to, fk_table) |>
    filter(table %in% tablesToJoin$table & fk_table %in% tablesToJoin$table) |>
    group_by(table, fk_table) |>
    mutate(linkId = cur_group_id()) |>
    ungroup()

  # duplicatedIDs <- table(c(tablesToJoin$from, tablesToJoin$to))
  # duplicatedIDs <- names(duplicatedIDs)[duplicatedIDs > 1]
  #
  # tablesToJoin |>
  #   mutate(
  #     uniqueFrom = ifelse(from %in% duplicatedIDs, to, from),
  #     uniqueTo = ifelse(to %in% duplicatedIDs, from, to)
  #   )

  # Make sure column names are unique to avoid joining issues
  dedupl <- schemainfo$tableInfo |>
    select(table, name, pk) |>
    filter(table %in% c(tablesToJoin$table, tablesToJoin$fk_table)) |>
    group_by(name) |>
    mutate(
      dupl = n() > 1,
      uniqueAttr = ifelse(dupl, paste0(name, "_", 1:n()), name)
    ) |>
    ungroup()

  tablesToJoin <- tablesToJoin |>
    left_join(
      dedupl |> select(table, from = name, fromUnique = uniqueAttr),
      by = c("table", "from")
    ) |>
    left_join(
      dedupl |> select(fk_table = table, to = name, toUnique = uniqueAttr),
      by = c("fk_table", "to")
    )

  # Start with the first listed table
  first <- c(
    which(toJoin[1] == tablesToJoin$table),
    which(toJoin[1] == tablesToJoin$fk_table)
  )
  nextLinkId <- tablesToJoin$linkId[first[1]]
  joined = c()
  result = ""

  # Function to add the select() function based on addSelect parameter
  selectPlaceholder <- function(cols, table) {
    # PK <- schemainfo$tableInfo |>
    #   filter(table == {{ table }}, pk == 1) |>
    #   pull(name)

    PK <- dedupl |> filter(pk == 1, table == {{ table }})

    PK <- ifelse(
      PK$name == PK$uniqueAttr,
      PK$name,
      glue(PK$uniqueAttr, '" = "', PK$name)
    )
    FK <- tablesToJoin |> filter(table == {{ table }})
    FK <- ifelse(
      FK$from == FK$fromUnique,
      FK$from,
      glue(FK$fromUnique, '" = "', FK$from)
    )
    ifelse(
      addSelect,
      glue(
        '") |> select("',
        paste(c(PK, FK), collapse = '","'),
        ifelse(table %in% toJoin, '", everything())', '")')
      ),
      ')'
    )
  }

  # Generate the code needed to join the tables
  while (length(nextLinkId) > 0) {
    nextJoin <- tablesToJoin |> filter(linkId == nextLinkId)

    if (result == "") {
      if (nextJoin$fk_table == toJoin[1]) {
        colnames(nextJoin) <- c(
          "fk_table",
          "to",
          "from",
          "table",
          "linkId",
          "toUnique",
          "fromUnique"
        )
      }
      # # First join must include the table primary keys
      # tablePK <- schemainfo$tableInfo |>
      #   filter(table %in% nextJoin$table, pk == 1) |>
      #   pull(name)

      result = glue(
        'tbl(conn, "',
        nextJoin$table,
        selectPlaceholder(unique(nextJoin$from), nextJoin$table),
        ' |>\n  left_join(tbl(conn, "',
        nextJoin$fk_table,
        selectPlaceholder(unique(nextJoin$to), nextJoin$fk_table),
        ', by = c("',
        nextJoin$fromUnique,
        '" = "',
        nextJoin$toUnique,
        '"))'
      )
    } else {
      # Subsequent joins
      check <- nextJoin$table %in% joined
      joinTable <- ifelse(check, nextJoin$fk_table, nextJoin$table)
      result = glue(
        result,
        ' |>\n left_join(tbl(conn, "',
        joinTable,
        selectPlaceholder(
          if (check) {
            unique(nextJoin$to)
          } else {
            unique(nextJoin$from)
          },
          joinTable
        ),
        ', by = c("',
        ifelse(check, nextJoin$fromUnique, nextJoin$toUnique),
        '" = "',
        ifelse(check, nextJoin$toUnique, nextJoin$fromUnique),
        '"))'
      )
    }
    # Prepare for the next join by picking a table that can be linked to the existing ones
    joined <- c(joined, nextJoin$table, nextJoin$fk_table)
    tablesToJoin <- tablesToJoin |> filter(linkId != nextLinkId)
    # # If the IDs which were joined are different, we have alter this for subsequent
    # # joins that will need the 'to' ID to join on (has become the from ID)
    # if (nextJoin$from != nextJoin$to) {
    #   tablesToJoin <- tablesToJoin |>
    #     left_join(
    #       nextJoin |> select(fk_table, to, newTo = from),
    #       by = c("fk_table", "to")
    #     ) |>
    #     mutate(to = ifelse(is.na(newTo), to, newTo))
    #   print(tablesToJoin)
    #   tablesToJoin <- tablesToJoin |>
    #     select(-newTo)
    # }
    nextLinkId <- tablesToJoin |>
      filter(table %in% joined | fk_table %in% joined) |>
      slice(1) |>
      pull(linkId)
  }

  # Check for column names that will clash when joined
  clashing <- schemainfo$tableInfo |>
    filter(table %in% toJoin) |>
    group_by(name) |>
    filter(pk == 0, n() > 1) |>
    ungroup()

  if (nrow(clashing) > 0 & warnClashes) {
    warning(
      "The following colums names clash when their tables are joined\n",
      dfAsText(as.data.frame(clashing |> select(table, column = name)))
    )
  }

  # Print and return the result
  print(result)
  invisible(result)
}
